#!/usr/bin/env bash
printf 'DB_PW=%s
DB_NAME=%s
DB_HOST=%s
DB_USER=%s
STRIPE_WEBHOOK_SECRET=%s
RESEND_SECRET=%s
DB_URL=postgres://$DB_USER:$DB_PW@$DB_HOST/$DB_NAME
AUTH_SECRET=%s
STRIPE_SKEY=%s
NEXT_PUBLIC_STRIPE_PKEY=%s
NEXT_PUBLIC_FB_API_KEY=%s
NEXT_PUBLIC_FB_AUTH_DOMAIN=%s
NEXT_PUBLIC_FB_PROJECT_ID=%s
NEXT_PUBLIC_FB_STORAGE_BUCKET=%s
NEXT_PUBLIC_FB_MESSAGING_SENDER_ID=%s
NEXT_PUBLIC_FB_APP_ID=%s
AUTH_GOOGLE_ID=%s
AUTH_GOOGLE_SECRET=%s
NEXT_PUBLIC_GOOGLE_MAP_API=%s
FB_ADMIN=%s
    ' "$DB_PW" "$DB_NAME" "$DB_HOST" "$DB_USER" "$STRIPE_WEBHOOK_SECRET" "$RESEND_SECRET" "$AUTH_SECRET" "$STRIPE_SKEY" "$STRIPE_PKEY" "$FB_API_KEY" "$FB_AUTH_DOMAIN" "$FB_PROJECT_ID" "$FB_STORAGE_BUCKET" "$FB_MESSAGING_SENDER_ID" "$FB_APP_ID" "$AUTH_GOOGLE_ID" "$AUTH_GOOGLE_SECRET" "$MAP_KEY" "$FB_ADMIN" > \
./.env.local